### ISSUE TITLE
Upgrade support for Angular 6.x

### ISSUE THREAD

**Issue by jonathan-bird** [alhazmy13/angular-csv#12]
Upgrade support for Angular 6.x please!

**Comment by alandroid** [comment]
https://github.com/kosmas58/angular6-csv

**Comment by jonathan-bird** [comment]
Alan, you need to create a tagged release to be able to save it via npm.

Thanks

**Comment by fedorax** [comment]
Hi 

we want to support this package (this package is angular5-csv). not angular6-csv.
because we should all script change if we use to change angular5-csv to angular6-csv.
and also angular7 and more schedule feature, then same change is too crazy.

**Comment by juliusiqbal** [comment]
Please add support for angular version 6

**Comment by alhazmy13** [comment]
Fixed with https://github.com/alhazmy13/angular-csv/pull/33
